2021-12-24 19:21:07,300 - E:\pythonProject\ServerWindow.py[line:28] - INFO: before handle,连接建立：('127.0.0.1', 62565)
2021-12-24 19:21:22,801 - E:\pythonProject\ServerWindow.py[line:23] - INFO: ('127.0.0.1', 62565)连接断开
2021-12-24 19:21:22,801 - E:\pythonProject\ServerWindow.py[line:31] - INFO: finish run  after handle
2021-12-24 19:25:37,968 - E:\pythonProject\ServerWindow.py[line:28] - INFO: before handle,连接建立：('127.0.0.1', 62671)
2021-12-24 19:28:35,479 - E:\pythonProject\ServerWindow.py[line:31] - INFO: finish run  after handle
2021-12-24 19:29:37,414 - E:\pythonProject\ServerWindow.py[line:28] - INFO: before handle,连接建立：('127.0.0.1', 62687)
2021-12-24 19:32:26,481 - E:\pythonProject\ServerWindow.py[line:23] - INFO: ('127.0.0.1', 62687)连接断开
2021-12-24 19:32:26,482 - E:\pythonProject\ServerWindow.py[line:31] - INFO: finish run  after handle
2021-12-24 19:37:51,720 - E:\pythonProject\ServerWindow.py[line:30] - INFO: before handle,连接建立：('127.0.0.1', 62789)
2021-12-24 19:38:08,790 - E:\pythonProject\ServerWindow.py[line:51] - INFO: b'except Exception as eLog.Logger.info(str(self.c1finallyself.request.cLose('显示失败
2021-12-24 19:41:31,550 - E:\pythonProject\ServerWindow.py[line:25] - INFO: ('127.0.0.1', 62789)连接断开
2021-12-24 19:41:31,551 - E:\pythonProject\ServerWindow.py[line:33] - INFO: finish run  after handle
2021-12-24 19:46:11,812 - E:\work_place\recongnition\ServerWindow.py[line:30] - INFO: before handle,连接建立：('127.0.0.1', 62411)
2021-12-24 19:47:37,076 - E:\work_place\recongnition\ServerWindow.py[line:51] - INFO: b"$rom ppstructurc.predi] u ~~11@~~Poddte0CR', PPSt"显示失败
2021-12-24 19:48:50,743 - E:\work_place\recongnition\ServerWindow.py[line:25] - INFO: ('127.0.0.1', 62411)连接断开
2021-12-24 19:48:50,743 - E:\work_place\recongnition\ServerWindow.py[line:33] - INFO: finish run  after handle
2021-12-24 19:55:25,846 - E:\work_place\recongnition\ServerWindow.py[line:30] - INFO: before handle,连接建立：('127.0.0.1', 62516)
2021-12-24 19:55:27,194 - E:\work_place\recongnition\ServerWindow.py[line:51] - INFO: b''显示失败
2021-12-24 19:55:27,195 - E:\work_place\recongnition\ServerWindow.py[line:33] - INFO: finish run  after handle
2021-12-24 19:56:04,208 - E:\work_place\recongnition\ServerWindow.py[line:64] - INFO: before handle,连接建立：('127.0.0.1', 62518)
2021-12-24 19:56:20,820 - E:\work_place\recongnition\ServerWindow.py[line:22] - INFO: b'dron Servertindon opor ServertindonAJ0donty0EOOOE'显示失败
2021-12-24 19:56:36,690 - E:\work_place\recongnition\ServerWindow.py[line:59] - INFO: ('127.0.0.1', 62518)连接断开
2021-12-24 19:56:36,690 - E:\work_place\recongnition\ServerWindow.py[line:67] - INFO: finish run  after handle
2021-12-24 20:08:51,304 - E:\work_place\recongnition\ServerWindow.py[line:55] - INFO: before handle,连接建立：('127.0.0.1', 64087)
2021-12-24 20:09:03,790 - E:\work_place\recongnition\ServerWindow.py[line:80] - INFO: b'0a0canucebcnchourkaP9la8.0dgdr/2.3.0.2\\\\CP\\\\cll.0gin'显示失败
2021-12-24 20:15:22,041 - E:\work_place\recongnition\ServerWindow.py[line:50] - INFO: ('127.0.0.1', 64087)连接断开
2021-12-24 20:15:22,042 - E:\work_place\recongnition\ServerWindow.py[line:58] - INFO: finish run  after handle
2021-12-24 21:35:10,297 - E:\work_place\recongnition\ServerWindow.py[line:102] - ERROR: read_data_slot: 寄
2021-12-24 21:35:45,777 - E:\work_place\recongnition\ServerWindow.py[line:102] - ERROR: read_data_slot: 寄
2021-12-24 21:37:18,282 - E:\work_place\recongnition\ServerWindow.py[line:105] - ERROR: read_data_slot2: 寄
2021-12-24 21:38:24,673 - E:\work_place\recongnition\ServerWindow.py[line:106] - ERROR: read_data_slot2: 寄
2021-12-24 21:39:29,705 - E:\work_place\recongnition\ServerWindow.py[line:98] - ERROR: read_data_slot1: 寄
2021-12-24 21:39:29,708 - E:\work_place\recongnition\ServerWindow.py[line:107] - ERROR: read_data_slot2: 寄
